In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import sklearn.preprocessing as preprocessing
import sklearn.model_selection as model_selection
import sklearn.metrics as metrics

In [4]:
from dotenv import load_dotenv
import os

load_dotenv(r"senha.env")

HOST = os.getenv("MYSQL_HOST")
USER = os.getenv("MYSQL_USER")
PASSWORD = os.getenv("MYSQL_PASSWORD")
DATABASE = os.getenv("MYSQL_DATABASE")

In [14]:
from sqlalchemy import create_engine
import pandas as pd
import time

engine = create_engine(
    f"mysql+pymysql://root:{PASSWORD}@localhost:3306/ENJOEEI_PROJECT"
)

today = 20260711

query = f"""
SELECT
    a.*
    ,b.fl_item_ativo
FROM ENJOEEI_PROJECT.produtos AS a
LEFT JOIN (
    SELECT
        link,
        fl_item_ativo,
        ROW_NUMBER() OVER (
            PARTITION BY link
            ORDER BY fl_item_ativo DESC
        ) AS rn
    FROM ENJOEEI_PROJECT.detalhe_produtos_enjoeei
) AS b
    ON a.url = b.link
   AND b.rn = 1
"""

df = pd.read_sql(query, con=engine)
df

,titulo,preco,preco_antigo,marca,tamanho,imagem,url,likes,tag,anomesdia_particao,categoria,fl_item_ativo
0,fone de ouvido tune 510bt preto,R$ 126,None,sem marca,,https://photos.enjoei.com.br/public/300x300/cz...,https://www.enjoei.com.br/p/fone-de-ouvido-tun...,0,None,20260709,None,1.0
1,massageador elétrico pescoço ombro lombar cinza,R$ 120,R$ 120,neck massager,,https://photos.enjoei.com.br/public/300x300/cz...,https://www.enjoei.com.br/p/massageador-eletri...,1,3%,20260709,None,1.0
2,kindle 11 geração preto,R$ 590,R$ 590,kindle,,https://photos.enjoei.com.br/public/300x300/cz...,https://www.enjoei.com.br/p/kindle-11-geracao-...,3,barateou,20260709,None,0.0
3,placa de vídeo palit rtx 3080 gamingpro 10gb,R$ 4.000,None,palit,,https://photos.enjoei.com.br/public/300x300/cz...,https://www.enjoei.com.br/p/placa-de-video-pal...,1,None,20260709,None,1.0
4,jogo kinect adventures xbox 360 original,R$ 45,R$ 45,sem marca,,https://photos.enjoei.com.br/public/300x300/cz...,https://www.enjoei.com.br/p/jogo-kinect-advent...,0,11%,20260709,None,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1930,rádio antigo colecionador década 50 60,R$ 529,R$ 529,philips,,https://photos.enjoei.com.br/public/300x300/cz...,https://www.enjoei.com.br/p/radio-antigo-colec...,7,barateou,20260718,eletronicos,NaN
1931,kit 3 câmeras analógicas kodak ekta,R$ 1.299,R$ 1.299,kodak,,https://photos.enjoei.com.br/public/300x300/cz...,https://www.enjoei.com.br/p/kit-3-cameras-anal...,1,barateou,20260718,eletronicos,NaN
1932,jogo the sims 3 para pc e mac,R$ 95,R$ 95,"ea,",,https://photos.enjoei.com.br/public/300x300/cz...,https://www.enjoei.com.br/p/jogo-the-sims-3-pa...,2,barateou,20260718,eletronicos,NaN
1933,jogo dragon ball xenoverse ps4,R$ 80,None,bandai namco,,https://photos.enjoei.com.br/public/300x300/cz...,https://www.enjoei.com.br/p/jogo-dragon-ball-x...,1,None,20260718,eletronicos,NaN
1934,capa celular samsung galaxy a05 roxa,R$ 25,R$ 25,samsung,,https://photos.enjoei.com.br/public/300x300/cz...,https://www.enjoei.com.br/p/capa-celular-samsu...,0,20%,20260718,eletronicos,NaN

In [ ]:
# 1. Qual é meu objetivo?
#         ↓
# 2. Qual coluna quero prever?
#         ↓
# 3. Quais colunas ajudam nessa previsão?
#         ↓
# 4. Que tipo de dado existe em cada coluna?
#         ↓
# 5. Cada tipo precisa de qual tratamento?
#         ↓
# 6. Agora sim treino o modelo.


pd.pivot_table(
    df,
    index='fl_item_ativo',
    values='url',
    aggfunc='count',
    dropna=False
)

                url
fl_item_ativo
0.0              57
1.0            1434
NaN             444